export {
  animeRouteFromCatalog,
  animeRouteSlug,
  catalogRouteSlug,
  findAnimeByRoute,
  findCatalogResultByRoute,
  getProfileIdFromPath,
  getRouteAnimeId,
  getViewFromPath,
  getWatchPartyCodeFromPath,
  normalizeWatchPartyCode,
  parseShikimoriRouteId,
  profileRoute,
  slugifyAnimeTitle,
  type AppView,
} from '@anima/core';
